name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: "Content"
      value: |
        # π™π¬πΈπ¦€π¦

        ## π™π™π™ γγ“ π™π™π™

        π™π™π™π™π™ π™π™π™π™π™ π™π™π™π™π™
        π™π™π™π™π™ π™π™π™π™π™ π™π™π™π™π™
        π™π™π™π™π™ π™π™π™π™π™ π™π™π™π™π™
        π™π™π™π™π™ π™π™π™π™π™ π™π™π™π™π™
        π™π™π™π™π™ π™π™π™π™π™ π™π™π™π™π™

        ## π¬π¬π¬ γ„γ‚‹γ‹ π¬π¬π¬

        π¬π¬π¬π¬π¬ π¬π¬π¬π¬π¬ π¬π¬π¬π¬π¬
        π¬π¬π¬π¬π¬ π¬π¬π¬π¬π¬ π¬π¬π¬π¬π¬
        π¬π¬π¬π¬π¬ π¬π¬π¬π¬π¬ π¬π¬π¬π¬π¬
        π¬π¬π¬π¬π¬ π¬π¬π¬π¬π¬ π¬π¬π¬π¬π¬
        π¬π¬π¬π¬π¬ π¬π¬π¬π¬π¬ π¬π¬π¬π¬π¬

        ## πΈπΈπΈ γ‹γγ‚‹ πΈπΈπΈ

        πΈπΈπΈπΈπΈ πΈπΈπΈπΈπΈ πΈπΈπΈπΈπΈ
        πΈπΈπΈπΈπΈ πΈπΈπΈπΈπΈ πΈπΈπΈπΈπΈ
        πΈπΈπΈπΈπΈ πΈπΈπΈπΈπΈ πΈπΈπΈπΈπΈ
        πΈπΈπΈπΈπΈ πΈπΈπΈπΈπΈ πΈπΈπΈπΈπΈ
        πΈπΈπΈπΈπΈ πΈπΈπΈπΈπΈ πΈπΈπΈπΈπΈ

        ## π¦€π¦€π¦€ γ‹γ« π¦€π¦€π¦€

        π¦€π¦€π¦€π¦€π¦€ π¦€π¦€π¦€π¦€π¦€ π¦€π¦€π¦€π¦€π¦€
        π¦€π¦€π¦€π¦€π¦€ π¦€π¦€π¦€π¦€π¦€ π¦€π¦€π¦€π¦€π¦€
        π¦€π¦€π¦€π¦€π¦€ π¦€π¦€π¦€π¦€π¦€ π¦€π¦€π¦€π¦€π¦€
        π¦€π¦€π¦€π¦€π¦€ π¦€π¦€π¦€π¦€π¦€ π¦€π¦€π¦€π¦€π¦€
        π¦€π¦€π¦€π¦€π¦€ π¦€π¦€π¦€π¦€π¦€ π¦€π¦€π¦€π¦€π¦€

        ## π¦π¦π¦ γ•γ‚ π¦π¦π¦

        π¦π¦π¦π¦π¦ π¦π¦π¦π¦π¦ π¦π¦π¦π¦π¦
        π¦π¦π¦π¦π¦ π¦π¦π¦π¦π¦ π¦π¦π¦π¦π¦
        π¦π¦π¦π¦π¦ π¦π¦π¦π¦π¦ π¦π¦π¦π¦π¦
        π¦π¦π¦π¦π¦ π¦π¦π¦π¦π¦ π¦π¦π¦π¦π¦
        π¦π¦π¦π¦π¦ π¦π¦π¦π¦π¦ π¦π¦π¦π¦π¦
